
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author neha
 */
public class neha extends javax.swing.JFrame {

    /**
     * Creates new form neha
     */
    public neha() {
        initComponents();
    }
    
    //method
    public static String IMDb(int movie){
        final int NUMBER = 4; //constant
        final int RATE = 10;//constant
        
        //arrays
        String title [] = new String [NUMBER];
        double rating [][] = new double [NUMBER][RATE];
        int ppl [][] = new int [NUMBER][RATE];
        String blank [] = new String [NUMBER];
        
        double [] IMDb = new double [NUMBER];
        
        //read file
        try{
            FileReader file = new FileReader("Movies.txt");
            
            BufferedReader buffer = new BufferedReader(file);
            for(int i = 0;i < NUMBER; i++){
                title[i] = buffer.readLine();
                System.out.println(title[i]);
                blank[i] = buffer.readLine();
                System.out.println(blank[i]);
                for(int j = 0; j < RATE; j++){
                    rating[i][j] = Double.parseDouble(buffer.readLine());
                    System.out.println(rating[i][j]);
                    ppl[i][j] = Integer.parseInt(buffer.readLine());
                    System.out.println(ppl[i][j]);
                }
            }
            buffer.close();
            
        }
        catch(IOException e){
            return ("Sorry file not found");
        }
        for(int i = 0; i < NUMBER; i++){
            IMDb[i] = 0;
            for(int j = 0; j < RATE; j++){
                IMDb[i] += (rating[i][j]/100)*(10-j);
            }
        }
        return (String.valueOf(IMDb[movie-1]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IMBd2 = new javax.swing.JLabel();
        IMBd3 = new javax.swing.JLabel();
        IMBd4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MOVIE1 = new javax.swing.JButton();
        MOVIE2 = new javax.swing.JButton();
        MOVIE3 = new javax.swing.JButton();
        MOVIE4 = new javax.swing.JButton();
        IMBd1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IMBd2.setText("-----");

        IMBd3.setText("-----");

        IMBd4.setText("-----");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Movie ratings ");

        MOVIE1.setText("The Amazing Spiderman");
        MOVIE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOVIE1ActionPerformed(evt);
            }
        });

        MOVIE2.setText("Back to the future");
        MOVIE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOVIE2ActionPerformed(evt);
            }
        });

        MOVIE3.setText("Inside Out");
        MOVIE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOVIE3ActionPerformed(evt);
            }
        });

        MOVIE4.setText("The Adam Project");
        MOVIE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOVIE4ActionPerformed(evt);
            }
        });

        IMBd1.setText("-----");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(MOVIE3)
                                .addGap(18, 18, 18)
                                .addComponent(IMBd3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(MOVIE2)
                                .addGap(18, 18, 18)
                                .addComponent(IMBd2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MOVIE1)
                                .addGap(18, 18, 18)
                                .addComponent(IMBd1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(MOVIE4)
                                .addGap(18, 18, 18)
                                .addComponent(IMBd4)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MOVIE1)
                    .addComponent(IMBd1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MOVIE2)
                    .addComponent(IMBd2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MOVIE3)
                    .addComponent(IMBd3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MOVIE4)
                    .addComponent(IMBd4))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MOVIE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOVIE1ActionPerformed
        // TODO add your handling code here:
        IMBd1.setText(IMDb(1)); //set label text
    }//GEN-LAST:event_MOVIE1ActionPerformed

    private void MOVIE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOVIE2ActionPerformed
        // TODO add your handling code here:
        IMBd2.setText(IMDb(2)); //set label text
    }//GEN-LAST:event_MOVIE2ActionPerformed

    private void MOVIE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOVIE3ActionPerformed
        // TODO add your handling code here:
        IMBd3.setText(IMDb(3)); //set label text
    }//GEN-LAST:event_MOVIE3ActionPerformed

    private void MOVIE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOVIE4ActionPerformed
        // TODO add your handling code here:
        IMBd4.setText(IMDb(4)); //set label text
    }//GEN-LAST:event_MOVIE4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(neha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(neha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(neha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(neha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new neha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMBd1;
    private javax.swing.JLabel IMBd2;
    private javax.swing.JLabel IMBd3;
    private javax.swing.JLabel IMBd4;
    private javax.swing.JButton MOVIE1;
    private javax.swing.JButton MOVIE2;
    private javax.swing.JButton MOVIE3;
    private javax.swing.JButton MOVIE4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
